# Generated by Django 5.0.2 on 2024-02-07 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('estado', models.CharField(choices=[('PE', 'Pendiente por iniciar'), ('EC', 'En curso'), ('IN', 'Inactivo'), ('FI', 'Finalizado'), ('OTRO', 'Otro')], default='IN', max_length=5)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('unidad', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=255)),
                ('periodo_academico', models.CharField(max_length=255)),
                ('crn', models.CharField(max_length=255)),
                ('intensidad_horaria_semanal', models.FloatField()),
                ('duracion_total_en_horas', models.FloatField()),
                ('requiere_asistente_de_experiencia', models.BooleanField()),
                ('requiere_asistencia_minima', models.BooleanField()),
                ('requiere_nota_minima', models.BooleanField()),
                ('porcentaje_asistencia_minima', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('orden_modulo', models.PositiveIntegerField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='programa.programa')),
            ],
            options={
                'ordering': ['orden_modulo'],
                'unique_together': {('programa', 'orden_modulo')},
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('orden_sesion', models.PositiveIntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='programa.modulo')),
            ],
            options={
                'ordering': ['orden_sesion'],
                'unique_together': {('modulo', 'orden_sesion')},
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_clase', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('orden_clase', models.PositiveIntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='programa.sesion')),
            ],
            options={
                'ordering': ['orden_clase'],
                'unique_together': {('sesion', 'orden_clase')},
            },
        ),
    ]
