# Generated by Django 5.0.2 on 2024-02-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['orden_sesion'], 'verbose_name': 'Sesion', 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.AddField(
            model_name='clase',
            name='ubicacion',
            field=models.CharField(choices=[('VI', 'Virtual'), ('PR', 'Presencial')], default='PR', max_length=5),
        ),
        migrations.AlterField(
            model_name='programa',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente por iniciar'), ('EC', 'En curso'), ('IN', 'Inactivo'), ('EJ', 'Ejecutado'), ('OTRO', 'Otro')], default='IN', max_length=5),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nota_minima',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='programa',
            name='unidad',
            field=models.CharField(choices=[('PAB', 'Programas Abiertos'), ('PCO', 'Programas Corporativos'), ('PRO', 'Proyectos'), ('MAE', 'Maestria'), ('ESP', 'Especializaciones'), ('PRE', 'Pregrado')], default='PAB', max_length=5),
        ),
    ]
