# Generated by Django 4.2.7 on 2023-11-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte'), ('OTRO', 'Otro')], default='CC', max_length=5)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('codigoUniandes', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('profesion', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('nacionalidad', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('celular', models.CharField(max_length=20)),
            ],
        ),
    ]
